name: Android CI

on:
  push:
    branches:
      - "**"
    tags:
      - v*
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install Build Tools 35.0.0
        run: sdkmanager "build-tools;35.0.0"

      - name: Verify installed SDK Packages
        run: sdkmanager --list

      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "2.9.9"
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: "ubuntulinux-ci"

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          link-to-sdk: true

      - name: Grant Execute Permission to gradlew
        run: chmod +x ./gradlew

      # Các bước build APK đã bị xóa/bỏ
      # - name: Build Debug and Unsigned Release APKs
      #   run: ./gradlew assembleDebug assembleRelease
      # - name: Upload Debug APK
      #   uses: actions/upload-artifact@v4.6.2
      #   with:
      #     name: LeviLauncher-debug-apk
      #     path: app/build/outputs/apk/debug/*.apk
      # - name: Upload Unsigned Release APK
      #   uses: actions/upload-artifact@v4.6.2
      #   with:
      #     name: LeviLauncher-release-unsigned-apk
      #     path: app/build/outputs/apk/release/*-unsigned.apk
      # - name: Sign Release APK
      # - name: Rename APK with tag
      # - name: Upload Signed APK Artifact
      # - name: Release APK to GitHub Releases
